In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

## Cleaning Data

In [4]:
df_dvf = pd.read_csv('raw_data/dvf.csv')

df_dvf.head(5)

/tmp/ipykernel_1983/861062116.py:1: DtypeWarning: Columns (2,4,5,9,10,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,31,32,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df_dvf = pd.read_csv('raw_data/dvf.csv')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
0,2021-1591389,2021-06-22,1,Vente en l'état futur d'achèvement,11945142.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.48192,48.900153,000AC
1,2021-1591389,2021-06-22,1,Vente en l'état futur d'achèvement,11945142.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.48192,48.900153,000AC
2,2021-1591389,2021-06-22,1,Vente en l'état futur d'achèvement,11945142.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.48192,48.900153,000AC
3,2021-1591389,2021-06-22,1,Vente en l'état futur d'achèvement,11945142.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.48192,48.900153,000AC
4,2021-1591389,2021-06-22,1,Vente en l'état futur d'achèvement,11945142.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.48192,48.900153,000AC

In [6]:
df_dvf['nature_mutation'].unique()

array(["Vente en l'état futur d'achèvement", 'Vente', 'Expropriation',
       'Echange', 'Vente terrain à bâtir', 'Adjudication',
       'nature_mutation'], dtype=object)

In [106]:
### Removing rows and columns###

df_dvf = df_dvf.dropna(subset=['valeur_fonciere', 'surface_reelle_bati', 'longitude'])
del_col =['adresse_suffixe', 'code_commune', 'nom_commune', 'code_departement', 'ancien_code_commune', 'ancien_nom_commune', 'ancien_id_parcelle', 'numero_volume', 'lot1_numero', 'lot1_surface_carrez', 'lot2_numero', 'lot2_surface_carrez', 'lot3_numero', 'lot3_surface_carrez', 'lot4_numero', 'lot4_surface_carrez', 'lot5_numero', 'lot5_surface_carrez', 'code_nature_culture', 'nature_culture', 'code_nature_culture_speciale', 'nature_culture_speciale', 'section_prefixe']
df_dvf = df_dvf.drop(columns = del_col)

df_dvf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55499 entries, 17 to 107198
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_mutation                55499 non-null  object
 1   date_mutation              55499 non-null  object
 2   numero_disposition         55499 non-null  object
 3   nature_mutation            55499 non-null  object
 4   valeur_fonciere            55499 non-null  object
 5   adresse_numero             55149 non-null  object
 6   adresse_nom_voie           55499 non-null  object
 7   adresse_code_voie          55499 non-null  object
 8   code_postal                55499 non-null  object
 9   id_parcelle                55499 non-null  object
 10  nombre_lots                55499 non-null  object
 11  code_type_local            55499 non-null  object
 12  type_local                 55499 non-null  object
 13  surface_reelle_bati        55499 non-null  object
 14  nombre_pieces_principales  55499 non-null  object
 15  surface_terrain            5247 non-null   object
 16  longitude                  55499 non-null  object
 17  latitude                   55499 non-null  object
dtypes: object(18)
memory usage: 8.0+ MB

In [107]:
### Formating data ####
df_dvf[['valeur_fonciere', 'surface_reelle_bati', 'nombre_pieces_principales', 'surface_terrain', 'longitude', 'latitude', 'code_postal', 'nombre_lots']] = df_dvf[['valeur_fonciere', 'surface_reelle_bati', 'nombre_pieces_principales', 'surface_terrain', 'longitude', 'latitude', 'code_postal', 'nombre_lots']].apply(lambda x: pd.to_numeric(x, errors='coerce').astype('float64'))


df_dvf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55499 entries, 17 to 107198
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_mutation                55499 non-null  object
 1   date_mutation              55499 non-null  object
 2   numero_disposition         55499 non-null  object
 3   nature_mutation            55499 non-null  object
 4   valeur_fonciere            55497 non-null  float64
 5   adresse_numero             55149 non-null  object
 6   adresse_nom_voie           55499 non-null  object
 7   adresse_code_voie          55499 non-null  object
 8   code_postal                55497 non-null  float64
 9   id_parcelle                55499 non-null  object
 10  nombre_lots                55497 non-null  float64
 11  code_type_local            55499 non-null  object
 12  type_local                 55499 non-null  object
 13  surface_reelle_bati        55497 non-null  float64
 14  nombre_pieces_principales  55497 non-null  float64
 15  surface_terrain            5245 non-null   float64
 16  longitude                  55497 non-null  float64
 17  latitude                   55497 non-null  float64
dtypes: float64(8), object(10)
memory usage: 8.0+ MB

In [108]:
df_dvf['prix_m_2'] = df_dvf['valeur_fonciere']/ df_dvf['surface_reelle_bati']



df_dvf.head(5)

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,id_parcelle,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude,prix_m_2
17,2022-60863,2022-06-21,1,Vente,630000.0,209.0,RTE DE BELLET,0745,6200.0,06088000MV0142,1.0,1.0,Maison,123.0,5.0,NaN,7.222367,43.703745,5121.951220
61,2021-53129,2021-01-07,1,Vente,175000.0,119.0,BD GAMBETTA,2755,6000.0,06088000MH0122,2.0,2.0,Appartement,44.0,2.0,NaN,7.255831,43.707262,3977.272727
62,2021-53130,2021-01-05,1,Vente,143600.0,166.0,BD DE LA MADELEINE,3820,6000.0,06088000ML0059,1.0,2.0,Appartement,50.0,2.0,NaN,7.236937,43.701856,2872.000000
63,2021-53132,2021-01-06,1,Vente,373500.0,144.0,RTE ST PIERRE FERIC,5910,6000.0,06088000LY0389,1.0,2.0,Appartement,66.0,3.0,NaN,7.240552,43.714549,5659.090909
64,2021-53133,2021-01-06,1,Vente,80450.0,5.0,RUE ABBE SALVETTI,0027,6300.0,06088000IY0079,1.0,2.0,Appartement,20.0,1.0,NaN,7.292555,43.703503,4022.500000

In [110]:
df_dvf['surface_terrain'].fillna(value=0, inplace=True)

df_dvf.head(5)

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,id_parcelle,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude,prix_m_2
17,2022-60863,2022-06-21,1,Vente,630000.0,209.0,RTE DE BELLET,0745,6200.0,06088000MV0142,1.0,1.0,Maison,123.0,5.0,0.0,7.222367,43.703745,5121.951220
61,2021-53129,2021-01-07,1,Vente,175000.0,119.0,BD GAMBETTA,2755,6000.0,06088000MH0122,2.0,2.0,Appartement,44.0,2.0,0.0,7.255831,43.707262,3977.272727
62,2021-53130,2021-01-05,1,Vente,143600.0,166.0,BD DE LA MADELEINE,3820,6000.0,06088000ML0059,1.0,2.0,Appartement,50.0,2.0,0.0,7.236937,43.701856,2872.000000
63,2021-53132,2021-01-06,1,Vente,373500.0,144.0,RTE ST PIERRE FERIC,5910,6000.0,06088000LY0389,1.0,2.0,Appartement,66.0,3.0,0.0,7.240552,43.714549,5659.090909
64,2021-53133,2021-01-06,1,Vente,80450.0,5.0,RUE ABBE SALVETTI,0027,6300.0,06088000IY0079,1.0,2.0,Appartement,20.0,1.0,0.0,7.292555,43.703503,4022.500000

In [111]:
df_dvf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55499 entries, 17 to 107198
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_mutation                55499 non-null  object
 1   date_mutation              55499 non-null  object
 2   numero_disposition         55499 non-null  object
 3   nature_mutation            55499 non-null  object
 4   valeur_fonciere            55497 non-null  float64
 5   adresse_numero             55149 non-null  object
 6   adresse_nom_voie           55499 non-null  object
 7   adresse_code_voie          55499 non-null  object
 8   code_postal                55497 non-null  float64
 9   id_parcelle                55499 non-null  object
 10  nombre_lots                55497 non-null  float64
 11  code_type_local            55499 non-null  object
 12  type_local                 55499 non-null  object
 13  surface_reelle_bati        55497 non-null  float64
 14  nombre_pieces_principales  55497 non-null  float64
 15  surface_terrain            55499 non-null  float64
 16  longitude                  55497 non-null  float64
 17  latitude                   55497 non-null  float64
 18  prix_m_2                   55497 non-null  float64
dtypes: float64(9), object(10)
memory usage: 8.5+ MB

In [112]:
df_dvf.head(5)

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,id_parcelle,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude,prix_m_2
17,2022-60863,2022-06-21,1,Vente,630000.0,209.0,RTE DE BELLET,0745,6200.0,06088000MV0142,1.0,1.0,Maison,123.0,5.0,0.0,7.222367,43.703745,5121.951220
61,2021-53129,2021-01-07,1,Vente,175000.0,119.0,BD GAMBETTA,2755,6000.0,06088000MH0122,2.0,2.0,Appartement,44.0,2.0,0.0,7.255831,43.707262,3977.272727
62,2021-53130,2021-01-05,1,Vente,143600.0,166.0,BD DE LA MADELEINE,3820,6000.0,06088000ML0059,1.0,2.0,Appartement,50.0,2.0,0.0,7.236937,43.701856,2872.000000
63,2021-53132,2021-01-06,1,Vente,373500.0,144.0,RTE ST PIERRE FERIC,5910,6000.0,06088000LY0389,1.0,2.0,Appartement,66.0,3.0,0.0,7.240552,43.714549,5659.090909
64,2021-53133,2021-01-06,1,Vente,80450.0,5.0,RUE ABBE SALVETTI,0027,6300.0,06088000IY0079,1.0,2.0,Appartement,20.0,1.0,0.0,7.292555,43.703503,4022.500000

In [113]:
import project

/Users/timotheehattemberg/Desktop/Projet_le_wagon/project.py:6: DtypeWarning: Columns (2,4,5,9,10,12,13,14,16,17,19,21,22,23,24,25,26,27,28,29,31,32,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df_dvf = pd.read_csv('dvf.csv')

In [114]:
df_dvf

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,id_parcelle,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,surface_terrain,longitude,latitude,prix_m_2
17,2022-60863,2022-06-21,1,Vente,630000.0,209.0,RTE DE BELLET,0745,6200.0,06088000MV0142,1.0,1.0,Maison,123.0,5.0,0.0,7.222367,43.703745,5121.951220
61,2021-53129,2021-01-07,1,Vente,175000.0,119.0,BD GAMBETTA,2755,6000.0,06088000MH0122,2.0,2.0,Appartement,44.0,2.0,0.0,7.255831,43.707262,3977.272727
62,2021-53130,2021-01-05,1,Vente,143600.0,166.0,BD DE LA MADELEINE,3820,6000.0,06088000ML0059,1.0,2.0,Appartement,50.0,2.0,0.0,7.236937,43.701856,2872.000000
63,2021-53132,2021-01-06,1,Vente,373500.0,144.0,RTE ST PIERRE FERIC,5910,6000.0,06088000LY0389,1.0,2.0,Appartement,66.0,3.0,0.0,7.240552,43.714549,5659.090909
64,2021-53133,2021-01-06,1,Vente,80450.0,5.0,RUE ABBE SALVETTI,0027,6300.0,06088000IY0079,1.0,2.0,Appartement,20.0,1.0,0.0,7.292555,43.703503,4022.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107189,2020-55959,2020-11-04,1,Vente,280000.0,83,BD MANTEGA RIGHI,3943,6100.0,06088000LW0407,2.0,2,Appartement,66.0,3.0,0.0,7.248990,43.712026,4242.424242
107193,2020-55961,2020-10-29,1,Vente,238000.0,23,AV LOUIS CAPPATTI,3734,6200.0,06088000OI0362,1.0,2,Appartement,48.0,2.0,0.0,7.207005,43.683574,4958.333333
107195,2020-55963,2020-10-26,1,Vente,500000.0,276,AV SAINTE MARGUERITE,6035,6200.0,06088000OL0212,1.0,1,Maison,61.0,4.0,0.0,7.202353,43.689002,8196.721311
107197,2020-55965,2020-10-13,1,Vente,140000.0,24,AV SAINT SYLVESTRE,5960,6100.0,06088000EH0271,1.0,2,Appartement,33.0,1.0,0.0,7.249229,43.725592,4242.424242
107198,2020-55966,2020-10-27,1,Vente,166000.0,143,BD DE CESSOLE,1265,6100.0,06088000EA0039,2.0,2,Appartement,53.0,2.0,0.0,7.249582,43.723532,3132.075472